package com.pjf.pjf.mapper;

import com.pjf.pjf.model.Question;
import org.springframework.stereotype.Repository;

@Repository
public interface QuestionExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Sun Feb 09 21:42:52 CST 2020
     */
    int incView(Question question);

}